apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    name: backend-app
spec:
  type: NodePort  
  ports:
    - port: 3003
      targetPort: 3003
      nodePort: 30006
      protocol: TCP
  selector:
    name: backend-app
    version: v1

