apiVersion: v1
kind: Service
metadata:
  name: migration-service
  labels:
    name: migration-app
spec:
  type: NodePort  
  ports:
    - port: 5438
      nodePort: 30007
      protocol: TCP
  selector:
    name: migration-app
    version: v1

